name: app_atex_gpt_exam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  csv: ^6.0.0
  dart_openai: ^5.1.0
  file_picker: ^8.0.0+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  media_store_plus: ^0.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
